//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanzerGeneral2_0.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PanzerGeneral2_0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cannon {
            get {
                object obj = ResourceManager.GetObject("cannon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap forest {
            get {
                object obj = ResourceManager.GetObject("forest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mountains {
            get {
                object obj = ResourceManager.GetObject("mountains", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plain {
            get {
                object obj = ResourceManager.GetObject("plain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap soldier {
            get {
                object obj = ResourceManager.GetObject("soldier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tank {
            get {
                object obj = ResourceManager.GetObject("tank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1
        ///1 1 1 0 0 0 0 0 0 1 0 0 1 1 1
        ///1 0 0 0 0 0 0 0 0 0 0 0 0 0 1
        ///0 0 0 1 0 0 2 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 2 2 0 0 1 0 0 0 1
        ///0 1 0 0 0 2 2 2 0 0 0 0 0 0 0
        ///0 0 0 0 0 2 2 2 2 0 0 0 0 1 0
        ///0 0 0 0 0 2 2 2 2 2 0 0 0 0 0
        ///
        ///0 -&gt; Plain
        ///1 -&gt; Forest
        ///2 -&gt; Mountains.
        /// </summary>
        public static string terrain_distribution {
            get {
                return ResourceManager.GetString("terrain_distribution", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 3 0 0 0 0 0 0 0 6 0 0 0
        ///0 2 0 3 0 0 0 0 0 0 0 6 0 5 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 1 0 0 0 0 0 0 0 0 0 4 0 0
        ///0 1 1 0 0 0 0 0 0 0 0 0 4 4 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///
        ///0 -&gt; no unit
        ///
        ///1 -&gt; team A Infantry
        ///2 -&gt; team A Cannon
        ///3 -&gt; team A Tank
        ///
        ///4 -&gt; team B Infantry
        ///5 -&gt; team B Cannon
        ///6 -&gt; team B Tank.
        /// </summary>
        public static string unit_distribution {
            get {
                return ResourceManager.GetString("unit_distribution", resourceCulture);
            }
        }
    }
}
