//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanzerGeneral2_0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PanzerGeneral2_0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap base_blue {
            get {
                object obj = ResourceManager.GetObject("base_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap base_red {
            get {
                object obj = ResourceManager.GetObject("base_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap board {
            get {
                object obj = ResourceManager.GetObject("board", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cannon {
            get {
                object obj = ResourceManager.GetObject("cannon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap forest {
            get {
                object obj = ResourceManager.GetObject("forest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frame_corner {
            get {
                object obj = ResourceManager.GetObject("frame_corner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap framed_side {
            get {
                object obj = ResourceManager.GetObject("framed_side", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap framed_top {
            get {
                object obj = ResourceManager.GetObject("framed_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap game_background_dark {
            get {
                object obj = ResourceManager.GetObject("game_background_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap maroon_texture {
            get {
                object obj = ResourceManager.GetObject("maroon_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap metal_plate_gold {
            get {
                object obj = ResourceManager.GetObject("metal_plate_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mountains {
            get {
                object obj = ResourceManager.GetObject("mountains", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plain {
            get {
                object obj = ResourceManager.GetObject("plain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap soldier {
            get {
                object obj = ResourceManager.GetObject("soldier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tank {
            get {
                object obj = ResourceManager.GetObject("tank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string terrain_distribution {
            get {
                return ResourceManager.GetString("terrain_distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string unit_distribution {
            get {
                return ResourceManager.GetString("unit_distribution", resourceCulture);
            }
        }
    }
}
