// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PanzerGeneral2_0.Databases;

namespace PanzerGeneral2_0.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20210118134349_Version_2")]
    partial class Version_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("PanzerGeneral2_0.DataModels.GameStateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentTurn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerTeamCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameState");
                });

            modelBuilder.Entity("PanzerGeneral2_0.DataModels.UnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YPosition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("canAttack")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("canMove")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
